language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/Argument_Complex/Argument_Complex.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/Argument_None/Argument_None.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/Argument_Simple/Argument_Simple.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/Change_Interval/Change_Interval.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/ISR_RPM_Measure/ISR_RPM_Measure.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/RPM_Measure/RPM_Measure.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/SwitchDebounce/SwitchDebounce.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/TimerDuration/TimerDuration.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/TimerInterruptTest/TimerInterruptTest.ino
